import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Nav2 from "@/components/Nav2";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="fixed top-0 z-50 w-screen bg-white">
          <Navbar />
          <Nav2 />
        </div>
        <main className="min-h-screen">
          {children}
        </main>
        <Footer />
      </body>
    </html >
  );
}
